### ISSUE TITLE
Command: "npm run setup-core" throws missing script error

### ISSUE THREAD

**Issue by andrijaf** [rolsen/ljswitchboard-project_manager#5]
Command
`npm run setup-core`
throws
`npm ERR! missing script: setup-core`

There are only the following scripts:
```
setup_all.js
setup_core_dev.js
setup_core_dist.js
setup.js
```

**Comment by rolsen** [comment]
The `re` branch is working on this kind of thing. Fix incoming this week, I expect.

**Comment by chrisJohn404** [comment]
This looks like another documentation issue.  Please run `npm run setup` to get the project set up for basic running of Kipling and use `npm run setup_all` for setting up the project for development.  I updated the README in the master branch to reflect this.
