### ISSUE TITLE
License needed

### ISSUE THREAD

**Issue by rolsen** [rolsen/ljswitchboard-project_manager#8]
The internet says it's [best to have an explicit license](https://softwareengineering.stackexchange.com/questions/26548/what-is-the-default-software-license).

**Comment by chrisJohn404** [comment]
I added a [license file](https://github.com/rolsen/ljswitchboard-project_manager/blob/master/LICENSE).  If it isn't the kind that you think we need, can you suggest some changes?

**Comment by rolsen** [comment]
Awesome. Closing this.
